### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [jr-consulting/kodilla-js8.5-repository#1]
- [x] zastosuj prosze uwagi z poprzedniego zadania
- [x] dla konsekwencji tutaj dodalbym spacje po znaku rownosci `var value =(a * a) + (2 * a * b) - (b * b);`
- [x] skrypt nie realizuje zalozen, powinny byc 3 opcje: wynik > 0, wynik < 0, wynik = 0

**Comment by jr-consulting** [comment]
poprawione

**Comment by zdolny** [comment]
blisko :) jeszcze pare poprawek:
- [ ] do usuniecia `<link rel="stylesheet" href="css/style.css">`
- [ ] popraw prosze spacje i wciecie w `if...else` zeby wygladalo to spojnie
- [ ] testowales moze wyniki, np dla `-1` i `-3`?

**Comment by zdolny** [comment]
yep :) poprawilem jeszcze jedno wciecie
